language: python
cache: pip
matrix:
  include:
  - python: '2.7'
  - python: '3.5'
  - python: '3.6'
  - python: '3.7'
  - python: '3.8'
  - python: 'nightly'
  - python: 'pypy'
  - python: 'pypy3'
install:
  - pip install setuptools -U
  - pip install -r requirements.txt -r devel-requirements.txt
  - pip install -e .
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then (make -C docs html); fi
  - bash tests/integration/management.sh
  - bash tests/integration/metrics.sh
